#server:
#  port: 10301
#
#spring:
#  application:
#    name: business-server

service-url:
  food-server: http://food-server
spring:
  profiles:
    active: dev # 表示开发环境
  #    active: test # 表示测试环境
  #    active: info

